### ISSUE TITLE
Check In

### ISSUE THREAD

**Issue by braidn** [DynamoMTL/ship_fosdick#1]
@bryanmtl and @peterberkenbosch just checking in here to see if the kickstart of this looks ok. I am still trying to wrap my brain around the fosdick thing. I guess just start by testing that we can create a csv out of order data?

**Comment by DanielWright** [comment]
What do you think of grabbing one of the CSVs that Wombat makes available to Fosdick, and using it as the "finish line"? You could reverse-engineer the order data to arrive at the "starting line" and then drive out the in-between with specs.

**Comment by bryanmtl** [comment]
@DanielWright Good idea. @braidn If you need one of these, I'll ship one to you this morning.

**Comment by braidn** [comment]
Absolutely need one! Thanks @bryanmtl

**Comment by peterberkenbosch** [comment]
@braidn should be a fair amount of samples here: https://github.com/DynamoMTL/fosdick_integration
