### ISSUE TITLE
Shipping Is Not Done On A Per Bucket Basis But With A URL Endpoint

### ISSUE THREAD

**Issue by braidn** [DynamoMTL/ship_fosdick#5]
There seems to be dual implementations in the wombat code([sender](https://github.com/wombat/fosdick_integration/blob/master/lib/sender.rb) versus [uploader](https://github.com/wombat/fosdick_integration/blob/master/lib/uploader.rb). @peterberkenbosch ever so sweetly brought this to my attention on Friday and it appears that the golden path in the wombat integration utilizes the endpoint/sender code.

cc @bryanmtl

**Comment by braidn** [comment]
Also, thanks for no markup in titles GH. :love_hotel: yah

**Comment by peterberkenbosch** [comment]
Thanks @braidn, will push some changes here soon for that!

**Comment by DanielWright** [comment]
I had a thought based on linking to Wombat repos: do we need to worry about those repos disappearing into the ether?

**Comment by DanielWright** [comment]
I had a thought based on linking to Wombat repos: do we need to worry about those repos disappearing into the ether?

**Comment by peterberkenbosch** [comment]
I have forked the fosdick one
